### ISSUE TITLE
.ofiles directory assumed to exist before make

### ISSUE THREAD

**Issue by kedoin** [Eyescale/Consensus#1]
Forgive me if I tried something ridiculous, but the first thing I attempted was to cd to Release/Version-1.1 and type "make" on my Kali Linux Linux subsystem on my PC. The first error was:

Assembler messages:
Fatal error: can't create .ofiles/database.o: No such file or directory
make: *** [Makefile:42: .ofiles/database.o] Error 1

Creating the .ofiles directory allowed make to proceed further.

**Comment by kedoin** [comment]
I wasn't sure if I should open this as a new issue or not, so I didn't. This same problem - assuming the .ofiles folder exists happens in the Makefile in the Base folder also.

**Comment by pbouchaud** [comment]
Thank you for your report. Yes I have been lazy with the Makefiles -maybe someday will do a proper job at it, but for now you are right: the .ofiles should be created manually first, anywhere there is a Makefile
