### ISSUE TITLE
Cannot link: /usr/bin/ld: cannot find -lcn

### ISSUE THREAD

**Issue by kedoin** [Eyescale/Consensus#2]
Again, running "make" in Release/Version-1.1.

cc -shared -o libbmod.so .ofiles/database.o .ofiles/db_debug.o .ofiles/db_io.o .ofiles/db_op.o .ofiles/context.o .ofiles/expression.o .ofiles/narrative.o .ofiles/operation.o .ofiles/traversal.o -L../../Base -lcn
/usr/bin/ld: cannot find -lcn
collect2: error: ld returned 1 exit status
make: *** [Makefile:38: libbmod.so] Error 1

**Comment by kedoin** [comment]
Noticed that there was another Makefile in Base that was in charge of making libcn. Ran make there.

Went back to Release/Version-1.1 and:

cc -shared -o libbmod.so .ofiles/database.o .ofiles/db_debug.o .ofiles/db_io.o .ofiles/db_op.o .ofiles/context.o .ofiles/expression.o .ofiles/narrative.o .ofiles/operation.o .ofiles/traversal.o -L../../Base -lcn
/usr/bin/ld: .ofiles/database.o: relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:38: libbmod.so] Error 1

**Comment by pbouchaud** [comment]
Sorry Rob (I suppose it's Rob, right?) Hadn't seen your messages for a year or more (just got back here with great new idea!!)
Sorry for the confusion with the Makefiles. Yes, as you found out, you are supposed to create the .ofiles directory manually both in Base and the Release/Version-xxx directories ; then make in Base first, then in your release directory ; and then again in the Examples
I don't see the last error you report, though...

**Comment by pbouchaud** [comment]
maybe try with make clean first everywhere...?
